"""cambio para que is_active se llene por default

Revision ID: 1a27a588986c
Revises: e8f7e2726986
Create Date: 2023-04-30 20:40:15.604093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a27a588986c'
down_revision = 'e8f7e2726986'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False,
               schema='authentication')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True,
               schema='authentication')
    # ### end Alembic commands ###
