"""unique constraint user group

Revision ID: 8bc24d1f0239
Revises: 7dc50707192b
Create Date: 2023-10-21 10:56:22.450835

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8bc24d1f0239'
down_revision = '7dc50707192b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_group_constraint', 'user_group_link', ['user_id', 'group_id'], schema='authentication')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_group_constraint', 'user_group_link', schema='authentication', type_='unique')
    # ### end Alembic commands ###
