"""Se crea restriccion unque de para id_user y id_group

Revision ID: 8dfd59996e3b
Revises: 06dd01cd7d16
Create Date: 2023-03-19 14:53:24.003317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfd59996e3b'
down_revision = '06dd01cd7d16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_1', 'users_groups', ['user_id', 'group_id'], schema='authentication')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_1', 'users_groups', schema='authentication', type_='unique')
    # ### end Alembic commands ###
