"""cambio anterior no se ve reflejado en base de datos por lo que se crea una nueva columna addres

Revision ID: 9e2f15c4baa3
Revises: bae51631679a
Create Date: 2022-12-18 17:21:03.509189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2f15c4baa3'
down_revision = 'bae51631679a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(), nullable=True), schema='authentication')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address', schema='authentication')
    # ### end Alembic commands ###
