"""se cambia valor por default de is_active a false

Revision ID: bae51631679a
Revises: 611c728b3c45
Create Date: 2022-12-18 17:14:50.803860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae51631679a'
down_revision = '611c728b3c45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
