"""se crea tabla para guardar passwords

Revision ID: e8f7e2726986
Revises: 8dfd59996e3b
Create Date: 2023-04-30 18:32:00.875212

"""
from alembic import op
import sqlalchemy as sa
from datamantainer_app.configs.settings import PASS_ADMIN
from datamantainer_app.models.authentication.passwords import Passwords


# revision identifiers, used by Alembic.
revision = 'e8f7e2726986'
down_revision = '8dfd59996e3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    table_password = op.create_table('passwords',
                                     sa.Column('id', sa.Integer(), nullable=False),
                                     sa.Column('user_id', sa.Integer(), nullable=False),
                                     sa.Column('hashed_password', sa.String(length=120), nullable=False),
                                     sa.Column('creation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                                     sa.Column('expiration_date', sa.Date(), nullable=True),
                                     sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
                                     sa.ForeignKeyConstraint(['user_id'], ['authentication.users.id'], ),
                                     sa.PrimaryKeyConstraint('id'),
                                     schema='authentication')

    op.create_index(op.f('ix_authentication_passwords_id'), 'passwords', ['id'], unique=False, schema='authentication')

    op.alter_column('groups', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='authentication')
    
    op.drop_index('ix_authentication_groups_description', table_name='groups', schema='authentication')

    op.create_index(op.f('ix_authentication_groups_code'), 'groups', ['code'], unique=True, schema='authentication')

    op.alter_column('users', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='authentication')
    
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='authentication')
    
    op.drop_column('users', 'hashed_password', schema='authentication')
    # ### end Alembic commands ###

    hashed_password = Passwords.set_password(PASS_ADMIN)

    password_admin = [{"user_id": 1, "hashed_password": hashed_password}]
    op.bulk_insert(table_password,
                   password_admin)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True), schema='authentication')

    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='authentication')
    
    op.alter_column('users', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='authentication')
    
    op.drop_index(op.f('ix_authentication_groups_code'), table_name='groups', schema='authentication')

    op.create_index('ix_authentication_groups_description', 'groups', ['description'], unique=False, schema='authentication')

    op.alter_column('groups', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='authentication')
    
    op.drop_index(op.f('ix_authentication_passwords_id'), table_name='passwords', schema='authentication')

    op.drop_table('passwords', schema='authentication')
    # ### end Alembic commands ###
