"""se agrega fullname a tabla users

Revision ID: eca9ccfab936
Revises: 6496e7e96b57
Create Date: 2023-03-12 15:30:51.272300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca9ccfab936'
down_revision = '6496e7e96b57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.String(), nullable=True), schema='authentication')
    op.execute("UPDATE authentication.users SET fullname='Nicolás Bacquet'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fullname', schema='authentication')
    # ### end Alembic commands ###
