# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: API Workflow

on:
  push:
    branches: [ "master" ]

jobs:
  build_app:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespw
          POSTGRES_DB: FastAPI_DB
        ports:
          - 5432:5432
          
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Connect to postgres
      working-directory: ./app
      run: alembic upgrade head
      env:
        DB_DRIVER: postgresql
        DB_ASYNC_DRIVER: asyncpg
        DB_USER: postgres
        DB_PASS: postgrespw
        DB_HOST: localhost
        DB_PORT: 5432
        DB_DATABASE_NAME: FastAPI_DB  
        SECRET_KEY: "WELL... NOTHING NEW, JUST THINKING ABOUT SECRETS"  
        ADMIN_EMAIL: ${{ secrets.MAIL_TEST }}
        PASS_ADMIN: ${{ secrets.PASSWORD_TEST }}
        USER_ADMIN: ${{ secrets.USER_TEST }}
        CRYPTO_KEY: ${{ secrets.CRYPTO_KEY_TEST}}
        DB_ASYNC_TEST: postgresql+asyncpg://postgres:postgrespw@localhost:5432/FastAPI_DB

    - name: Unit Test
      run: pytest --junitxml=res-test.xml
      env:
        SECRET_KEY: "WELL... NOTHING NEW, JUST THINKING ABOUT SECRETS"
        DB_DRIVER: postgresql
        DB_ASYNC_DRIVER: asyncpg
        DB_USER: postgres
        DB_PASS: postgrespw
        DB_HOST: localhost
        DB_PORT: 5432
        DB_DATABASE_NAME: FastAPI_DB
        ADMIN_EMAIL: ${{ secrets.MAIL_TEST }}
        USER_ADMIN: ${{ secrets.USER_TEST }}
        PASS_ADMIN: ${{ secrets.PASSWORD_TEST }}
        JWT_SECRET: please_please_update_me_please
        JWT_ALGORITHM: HS256
        SENTRY_DNS: ${{ secrets.SENTRY_DNS }}
        CRYPTO_KEY: ${{ secrets.CRYPTO_KEY_TEST}}
        B_ASYNC_TEST: postgresql+asyncpg://postgres:postgrespw@localhost:5432/FastAPI_DB
        
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure()
      with:
        report_paths: 'res-test.xml'
